=== sysrpl/SANTA-PENGUIN/examples/santa.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <xs:attributeGroup name="idable">
        <xs:attribute name="id" type="xs:ID"/>
        <xs:attribute name="ref" type="xs:NCName"/>
    </xs:attributeGroup>

    <xs:element name="santa">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="replicates" type="xs:string"/>
                <xs:element ref="simulation"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="simulation">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="genome"/>
                <xs:element ref="population"/>
                <xs:element ref="fitnessFunction"/>
                <xs:element ref="mutator"/>
                <xs:element ref="replicator"/>
                <xs:element minOccurs="1" maxOccurs="unbounded" ref="epoch"/>
                <xs:element ref="samplingSchedule"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="genome">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="length" type="xs:string"/>
                <xs:element minOccurs="0" name="sequences" type="xs:string"/>
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="feature"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="feature">
        <xs:complexType>
            <xs:all>
                <xs:element name="name" type="xs:string"/>
                <xs:element name="type">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="nucleotide"/>
                            <xs:enumeration value="aminoAcid"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="coordinates" type="xs:string"/>
            </xs:all>
        </xs:complexType>
    </xs:element>

    <xs:element name="population">
        <xs:complexType>
            <xs:all>
                <xs:element name="populationSize" type="xs:string"/>
                <xs:element name="inoculum">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="consensus"/>
                            <xs:enumeration value="random"/>
                            <xs:enumeration value="all"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
            </xs:all>
        </xs:complexType>
    </xs:element>

    <xs:element name="epoch">
        <xs:complexType>
            <xs:all>
                <xs:element minOccurs="0" name="name" type="xs:string"/>
                <xs:element name="generationCount" type="xs:string"/>
                <xs:element minOccurs="0" ref="fitnessFunction"/>
                <xs:element minOccurs="0" ref="mutator"/>
                <xs:element minOccurs="0" ref="replicator"/>
            </xs:all>
        </xs:complexType>
    </xs:element>

    <xs:element name="fitnessFunction">
        <xs:complexType>
            <xs:choice minOccurs="1" maxOccurs="unbounded">
                <xs:element ref="purifyingFitness"/>
                <xs:element ref="empiricalFitness"/>
                <xs:element ref="ageDependentFitness"/>
                <xs:element ref="exposureDependentFitness"/>
                <xs:element ref="populationSizeDependentFitness"/>
                <xs:element ref="frequencyDependentFitness"/>
                <xs:element ref="neutralFitness"/>
            </xs:choice>
            <xs:attributeGroup ref="idable"/>
        </xs:complexType>
    </xs:element>

    <xs:group name="feature-sites">
        <xs:sequence>
            <xs:element minOccurs="0" name="feature" type="xs:NCName"/>
            <xs:element minOccurs="0" name="sites" type="xs:string"/>
        </xs:sequence>
    </xs:group>

    <xs:element name="purifyingFitness">
        <xs:complexType>
            <xs:sequence minOccurs="0">
                <xs:group ref="feature-sites"/>
                <xs:element name="rank">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element minOccurs="1" maxOccurs="1" name="order" type="xs:string"/>
                            <xs:element minOccurs="0" maxOccurs="1" name="probableSet" type="xs:string"/>
                            <xs:element minOccurs="1" maxOccurs="1" name="breakTies">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="random"/>
                                        <xs:enumeration value="ordered"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="fitness">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:choice>
                                <xs:sequence>
                                    <xs:element name="lowFitness" type="xs:string"/>
                                    <xs:element name="minimumFitness" type="xs:string"/>
                                </xs:sequence>
                                <xs:element name="values" type="xs:string"/>
                                <xs:element name="betaDistributed">
                                    <xs:complexType>
                                        <xs:sequence>
                                            <xs:element name="a" type="xs:string"/>
                                            <xs:element name="b" type="xs:string"/>
                                            <xs:element name="pLethal" type="xs:string"/>
                                        </xs:sequence>
                                    </xs:complexType>
                                </xs:element>
                            </xs:choice>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element minOccurs="0" maxOccurs="1" name="fluctuate">
                    <xs:complexType>
                        <xs:all>
                            <xs:element name="fitnessLimit" type="xs:string"/>
                            <xs:element name="rate" type="xs:string"/>
                        </xs:all>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attributeGroup ref="idable"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="empiricalFitness">
        <xs:complexType>
            <xs:sequence minOccurs="0">
                <xs:group ref="feature-sites"/>
                <xs:element name="values" type="xs:string"/>
            </xs:sequence>
            <xs:attributeGroup ref="idable"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="ageDependentFitness">
        <xs:complexType>
            <xs:sequence minOccurs="0">
                <xs:group ref="feature-sites"/>
                <xs:element name="declineRate" type="xs:string"/>
            </xs:sequence>
            <xs:attributeGroup ref="idable"/>
        </xs:complexType>
    </xs:element>

<xs:element name="populationSizeDependentFitness">
        <xs:complexType>
            <xs:sequence minOccurs="0">
                <xs:group ref="feature-sites"/>
                <xs:element name="declineRate" type="xs:string"/>
                <xs:element name="maxPopulationSize" type="xs:string"/>
            </xs:sequence>
            <xs:attributeGroup ref="idable"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="exposureDependentFitness">
        <xs:complexType>
            <xs:sequence minOccurs="0">
                <xs:group ref="feature-sites"/>
                <xs:element name="penalty" type="xs:string"/>
            </xs:sequence>
            <xs:attributeGroup ref="idable"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="frequencyDependentFitness">
        <xs:complexType>
            <xs:sequence minOccurs="0">
                <xs:group ref="feature-sites"/>
                <xs:element name="shape" type="xs:string"/>
            </xs:sequence>
            <xs:attributeGroup ref="idable"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="neutralFitness">
        <xs:complexType>
            <xs:sequence minOccurs="0">
                <xs:group ref="feature-sites"/>
            </xs:sequence>
            <xs:attributeGroup ref="idable"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="mutator">
        <xs:complexType>
            <xs:all>
                <xs:element ref="nucleotideMutator"/>
            </xs:all>
        </xs:complexType>
    </xs:element>

    <xs:element name="nucleotideMutator">
        <xs:complexType>
            <xs:sequence minOccurs="0">
                <xs:element name="mutationRate" type="xs:string"/>
                <xs:choice>
                    <xs:element name="transitionBias" type="xs:string"/>
                    <xs:element name="rateBias" type="xs:string"/>
                </xs:choice>
            </xs:sequence>
            <xs:attributeGroup ref="idable"/>
        </xs:complexType>
    </xs:element>


    <xs:element name="replicator">
        <xs:complexType>
            <xs:choice>
                <xs:element ref="clonalReplicator"/>
                <xs:element ref="recombinantReplicator"/>
            </xs:choice>
        </xs:complexType>
    </xs:element>

    <xs:element name="clonalReplicator">
        <xs:complexType>
            <xs:attributeGroup ref="idable"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="recombinantReplicator">
        <xs:complexType>
            <xs:sequence minOccurs="0">
                <xs:element name="dualInfectionProbability" type="xs:string"/>
                <xs:element name="recombinationProbability" type="xs:string"/>
            </xs:sequence>
            <xs:attributeGroup ref="idable"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="samplingSchedule">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="sampler"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="sampler">
        <xs:complexType>
            <xs:sequence>
                <xs:choice>
                    <xs:element name="atFrequency" type="xs:string"/>
                    <xs:element name="atGeneration" type="xs:string"/>
                </xs:choice>
                <xs:element name="fileName" type="xs:string"/>
                <xs:choice>
                    <xs:element ref="alleleFrequency"/>
                    <xs:element ref="alignment"/>
                    <xs:element ref="tree"/>
                    <xs:element ref="statistics"/>
                </xs:choice>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="alleleFrequency">
        <xs:complexType>
            <xs:all>
                <xs:element minOccurs="0" name="feature" type="xs:string"/>
                <xs:element minOccurs="0" name="sites" type="xs:string"/>
            </xs:all>
        </xs:complexType>
    </xs:element>

    <xs:element name="alignment">
        <xs:complexType>
            <xs:sequence>
                <xs:choice>
                    <xs:element ref="schedule"/>
                    <xs:element name="sampleSize" type="xs:positiveInteger"/>
                </xs:choice>
                <xs:element name="format">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="NEXUS"/>
                            <xs:enumeration value="FASTA"/>
                            <xs:enumeration value="XML"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element minOccurs="0" maxOccurs="1" name="label" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="tree">
        <xs:complexType>
            <xs:sequence>
                <xs:choice>
                    <xs:element ref="schedule"/>
                    <xs:element name="sampleSize" type="xs:positiveInteger"/>
                </xs:choice>
                <xs:element name="format">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="NEXUS"/>
                            <xs:enumeration value="NEWICK"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element minOccurs="0" maxOccurs="1" name="label" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="schedule">
        <xs:simpleType>
            <xs:list itemType="xs:positiveInteger"/>
        </xs:simpleType>
    </xs:element>

    <xs:element name="statistics"/>
</xs:schema>

=== sysrpl/SANTA-PENGUIN/examples/simpleRecombination.xml
<santa xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="santa.xsd">

        <replicates>1</replicates>

        <simulation>

            <genome>
                <length>1302</length>
	            <sequences>
	                CCTCAGGTCACTCTTTGGCAACGACCCCTCGTCACAATAAAGATAGGGGGGCAACTAAAGGAAGCTCTATTAGATACAGGAGCAGATGATACAGTATTAGAAGAAATGAGTTTGCCAGGAAGATGGAAACCAAAAATGATAGGGGGAATTGGAGGTTTTATCAAAGTAAGACAGTATGATCAGATACTCATAGAAATCTGTGGACATAAAGCTATAGGTACAGTATTAGTAGGACCTACACCTGTCAACATAATTGGAAGAAATCTGTTGACTCAGATTGGTTGCACTTTAAATTTTCCCATTAGCCCTATTGAGACTGTACCAGTAAAATTAAAGCCAGGAATGGATGGCCCAAAAGTTAAACAATGGCCATTGACAGAAGAAAAAATAAAAGCATTAGTAGAAATTTGTACAGAGATGGAAAAGGAAGGGAAAATTTCAAAAATTGGGCCTGAAAATCCATACAATACTCCAGTATTTGCCATAAAGAAAAAAGACAGTACTAAATGGAGAAAATTAGTAGATTTCAGAGAACTTAATAAGAGAACTCAAGACTTCTGGGAAGTTCAATTAGGAATACCACATCCCGCAGGGTTAAAAAAGAAAAAATCAGTAACAGTACTGGATGTGGGTGATGCATATTTTTCAGTTCCCTTAGATGAAGACTTCAGGAAGTATACTGCATTTACCATACCTAGTATAAACAATGAGACACCAGGGATTAGATATCAGTACAATGTGCTTCCACAGGGATGGAAAGGATCACCAGCAATATTCCAAAGTAGCATGACAAAAATCTTAGAGCCTTTTAGAAAACAAAATCCAGACATAGTTATCTATCAATACATGGATGATTTGTATGTAGGATCTGACTTAGAAATAGGGCAGCATAGAACAAAAATAGAGGAGCTGAGACAACATCTGTTGAGGTGGGGACTTACCACACCAGACAAAAAACATCAGAAAGAACCTCCATTCCTTTGGATGGGTTATGAACTCCATCCTGATAAATGGACAGTACAGCCTATAGTGCTGCCAGAAAAAGACAGCTGGACTGTCAATGACATACAGAAGTTAGTGGGGAAATTGAATTGGGCAAGTCAGATTTACCCAGGGATTAAAGTAAGGCAATTATGTAAACTCCTTAGAGGAACCAAAGCACTAACAGAAGTAATACCACTAACAGAAGAAGCAGAGCTAGAACTGGCAGAAAACAGAGAGATTCTAAAAGAACCAGTACATGGAGTGTATTATGACCCATCAAAAGACTTAATAGCAGAAATACAGAAGCAGGGGCAAGGC
	            </sequences>
	            <feature>
		            <name>CDS</name>
		            <type>aminoAcid</type>
		            <coordinates>1-1302</coordinates>
	            </feature>
           </genome>

            <population>
                <populationSize>1000</populationSize>
	            <inoculum>all</inoculum>
            </population>
		
		<populationType>staticPopulation</populationType>


	

            <fitnessFunction>
                <purifyingFitness id="background">
	                <feature>CDS</feature>
	                <sites>1-201,203-279,281-434</sites>
                	<rank>
                		<order>observed</order>
                        <probableSet>3</probableSet>
                		<breakTies>random</breakTies>
                	</rank>
                	<fitness>
                		<lowFitness>0.9</lowFitness>
		                <minimumFitness>0.1</minimumFitness>
                	</fitness>
                </purifyingFitness>
                <empiricalFitness id="RC103">
	                <feature>CDS</feature>
	                <sites>202</sites>
                    <!-- REPLICATION CAPACITY 103 -->
                    <values>
                        0.01 <!-- A -->
                        0.01 <!-- C -->
                        0.01 <!-- D -->
                        0.01 <!-- E -->
                        0.01 <!-- F-->
                        0.01 <!-- G -->
                        0.01 <!-- H -->
                        0.01 <!-- I -->
                        1    <!-- K -->
                        0.01 <!-- L -->
                        0.01 <!-- M -->
                        0.85 <!-- N -->
                        0.01 <!-- P -->
                        0.01 <!-- Q -->
                        0.01 <!-- R -->
                        0.01 <!-- S -->
                        0.01 <!-- T -->
                        0.01 <!-- V -->
                        0.01 <!-- W -->
                        0.01 <!-- Y -->
                    </values>
                </empiricalFitness>
                <empiricalFitness id="RC181">
	                <feature>CDS</feature>
	                <sites>280</sites>
                    <!-- REPLICATION CAPACITY 181 -->
                    <values>
                        0.01 <!-- A -->
                        0.70 <!-- C -->
                        0.01 <!-- D -->
                        0.01 <!-- E -->
                        0.01 <!-- F-->
                        0.01 <!-- G -->
                        0.01 <!-- H -->
                        0.01 <!-- I -->
                        0.01 <!-- K -->
                        0.01 <!-- L -->
                        0.01 <!-- M -->
                        0.01 <!-- N -->
                        0.01 <!-- P -->
                        0.01 <!-- Q -->
                        0.01 <!-- R -->
                        0.01 <!-- S -->
                        0.01 <!-- T -->
                        0.01 <!-- V -->
                        0.01 <!-- W -->
                        1 <!-- Y -->
                    </values>
                </empiricalFitness>
            </fitnessFunction>

	        <mutator>
	            <nucleotideMutator>
	                <mutationRate>2.5E-5</mutationRate>
	                <rateBias>
	                    0.42 2.49 0.29
	                    1.73 0.23 4.73
	                    6.99 0.20 0.60
	                    1.02 2.56 0.88
	                </rateBias>
	            </nucleotideMutator>
	        </mutator>

	        <replicator>
	            <recombinantReplicator>
			<dualInfectionProbability>0.05</dualInfectionProbability>
			<recombinationProbability>0.001</recombinationProbability>
		</recombinantReplicator>
	        </replicator>

            <epoch>
                <name>epoch1</name>
                <generationCount>500</generationCount>
            </epoch>

           
            <samplingSchedule>

                <sampler>
                    <atFrequency>1</atFrequency>
                    <fileName>puri01psE4_freqRT103.csv</fileName>
                    <alleleFrequency>
	                    <feature>CDS</feature>
                        <sites>202</sites>
                    </alleleFrequency>
                </sampler>
                <sampler>
                    <atFrequency>1</atFrequency>
                    <fileName>puri01psE4_freqRT181.csv</fileName>
                    <alleleFrequency>
	                    <feature>CDS</feature>
                        <sites>280</sites>
                    </alleleFrequency>
                </sampler>
            </samplingSchedule>
        </simulation>
</santa>

=== sysrpl/SANTA-PENGUIN/examples/fluctuating.xml
<santa xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="santa.xsd">
	<replicates>1</replicates>

	<simulation>
		<genome>
			<length>1218</length>
			<sequences>
				GAAGAAGAGGTAGTAATTAGATCTGAAAATTTCACGGACAATGCTAAAACCATAATAGTACAGCTGAAGGAGTCTGTAGTAATTAATTGTACAAGACCCAATAACAATACAAGAAAAAGTATACAGGTAGGACCAGGGAAAGCAATTTATACAACAGGAGAAATAATAGGAGATTTAAGACAAGCACATTGTAACCTTAGTAGAGCAGAATGGAATAACACTTTAAAACAGATAGTTAAGAAATTAAGAGAACAATTTGGGAATAAAACAATAGTCTTTAATCAATCCTCAGGAGGGGACCCAGAAATTGTAATGCACAGTTTGAATTGTAGAGGGGAATTTTTCTACTGTAATTCAACACAACTGTTTAATAGTACTTGGGATAATAGTACTTTGAATAATGTTACTGAAGGGTCAAATAGCACTGAAGAGAATATCACACTCCCATGCAGAATAAAACAAATTATAAACATGTGGCAGGAAGTAGGAAAAGCAATGTATGCCCCTCCCATCAGAGGACAAATTAGATGTTCATCAAATATTACAGGGCTGCTATTAACAAGAGATGGTGGTAAGGACACGAGCAATACCGAAATCTTCAGACCTGGAGAAGAAGAGGTAGTAATTAGATCTGAAAATTTCACGGACAATGCTAAAACCATAATAGTACAGCTGAAGGAGTCTGTAGTAATTAATTGTACAAGACCCAATAACAATACAAGAAAAAGTATACAGGTAGGACCAGGGAAAGCAATTTATACAACAGGAGAAATAATAGGAGATTTAAGACAAGCACATTGTAACCTTAGTAGAGCAGAATGGAATAACACTTTAAAACAGATAGTTAAGAAATTAAGAGAACAATTTGGGAATAAAACAATAGTCTTTAATCAATCCTCAGGAGGGGACCCAGAAATTGTAATGCACAGTTTGAATTGTAGAGGGGAATTTTTCTACTGTAATTCAACACAACTGTTTAATAGTACTTGGGATAATAGTACTTTGAATAATGTTACTGAAGGGTCAAATAGCACTGAAGAGAATATCACACTCCCATGCAGAATAAAACAAATTATAAACATGTGGCAGGAAGTAGGAAAAGCAATGTATGCCCCTCCCATCAGAGGACAAATTAGATGTTCATCAAATATTACAGGGCTGCTATTAACAAGAGATGGTGGTAAGGACACGAGCAATACCGAAATCTTCAGACCTGGA
			</sequences>
			<feature>
				<name>CDS</name>
				<type>aminoAcid</type>
				<coordinates>1-1218</coordinates>
			</feature>
		</genome>

		<population>
			<populationSize>10000</populationSize>

			<inoculum>all</inoculum>
		</population>

		<fitnessFunction>
			<purifyingFitness>
				<feature>CDS</feature>
				<sites>6-203</sites>
				<rank>
					<order>observed</order>
					<breakTies>random</breakTies>
                </rank>
				<fitness>
					<values>1 0.9 0.8 0.7 0.6 0.5 0.4 0.3 0.2 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1</values>
				</fitness>
			</purifyingFitness>
			<purifyingFitness>
				<feature>CDS</feature>
				<sites>1-5</sites>
				<rank>
					<order>observed</order>
 					<breakTies>random</breakTies>
				</rank>
				<fitness>
					<values>1 0.9 0.8 0.7 0.6 0.5 0.4 0.3 0.2 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1</values>
				</fitness>
				<fluctuate>
					<rate>0.001</rate>
					<fitnessLimit>0</fitnessLimit>
				</fluctuate>
			</purifyingFitness>
		</fitnessFunction>

		<mutator>
			<nucleotideMutator>
				<mutationRate>2.5E-5</mutationRate>
				<transitionBias>2.0</transitionBias>
			</nucleotideMutator>
		</mutator>

		<replicator>
			<clonalReplicator/>
		</replicator>

		<epoch>
			<generationCount>2001</generationCount>
		</epoch>

		<samplingSchedule>
			<sampler>
				<atFrequency>100</atFrequency>
				<fileName>fluctuate_%r.nex</fileName>
				<alignment>
					<schedule>
						1200 10
						1400 10
						1600 10
						1800 10
						2000 10
					</schedule>
					<format>NEXUS</format>
					<label>fluctuate_%g_%s</label>
				</alignment>
			</sampler>
			<sampler>
				<atFrequency>1</atFrequency>
				<fileName>fluctuate_%r.csv</fileName>
				<statistics></statistics>
			</sampler>
		</samplingSchedule>

	</simulation>

</santa>

=== sysrpl/SANTA-PENGUIN/examples/neutral.xml
<santa xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="santa.xsd">
	<replicates>10</replicates>

	<simulation>
		<genome>
			<length>609</length>
			<sequences>
				GAAGAAGAGGTAGTAATTAGATCTGAAAATTTCACGGACAATGCTAAAACCATAATAGTACAGCTGAAGGAGTCTGTAGTAATTAATTGTACAAGACCCAATAACAATACAAGAAAAAGTATACAGGTAGGACCAGGGAAAGCAATTTATACAACAGGAGAAATAATAGGAGATTTAAGACAAGCACATTGTAACCTTAGTAGAGCAGAATGGAATAACACTTTAAAACAGATAGTTAAGAAATTAAGAGAACAATTTGGGAATAAAACAATAGTCTTTAATCAATCCTCAGGAGGGGACCCAGAAATTGTAATGCACAGTTTGAATTGTAGAGGGGAATTTTTCTACTGTAATTCAACACAACTGTTTAATAGTACTTGGGATAATAGTACTTTGAATAATGTTACTGAAGGGTCAAATAGCACTGAAGAGAATATCACACTCCCATGCAGAATAAAACAAATTATAAACATGTGGCAGGAAGTAGGAAAAGCAATGTATGCCCCTCCCATCAGAGGACAAATTAGATGTTCATCAAATATTACAGGGCTGCTATTAACAAGAGATGGTGGTAAGGACACGAGCAATACCGAAATCTTCAGACCTGGA
			</sequences>
			<feature>
				<name>CDS</name>
				<type>aminoAcid</type>
				<coordinates>1-609</coordinates>
			</feature>
		</genome>

		<population>
			<populationSize>10000</populationSize>

			<inoculum>all</inoculum>
		</population>

		<fitnessFunction>
            <neutralFitness>
	            <feature>CDS</feature>
	            <sites>1-203</sites>
            </neutralFitness>
        </fitnessFunction>

		<mutator>
			<nucleotideMutator>
				<mutationRate>1.0E-4</mutationRate>
				<transitionBias>2.0</transitionBias>
			</nucleotideMutator>
		</mutator>

		<replicator>
			<clonalReplicator/>
		</replicator>

		<epoch>
			<generationCount>1001</generationCount>
		</epoch>

		<samplingSchedule>
			<sampler>
				<atFrequency>100</atFrequency>
				<fileName>neutral_%r.nex</fileName>
				<alignment>
					<schedule>
						<!-- generation count -->
						200  10
						400  10
						600  10
						800  10
						1000  10
					</schedule>
					<format>NEXUS</format>
					<label>neutral_%g_%s</label>
				</alignment>
			</sampler>
			<sampler>
				<atFrequency>1</atFrequency>
				<fileName>neutral_%r.csv</fileName>
				<statistics></statistics>
			</sampler>
		</samplingSchedule>

	</simulation>

</santa>

=== sysrpl/SANTA-PENGUIN/examples/purifyingBeta.xml
<santa xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="santa.xsd">

    <replicates>10</replicates>

    <simulation>
        <genome>
            <length>609</length>
            <sequences>
                GAAGAAGAGGTAGTAATTAGATCTGAAAATTTCACGGACAATGCTAAAACCATAATAGTACAGCTGAAGGAGTCTGTAGTAATTAATTGTACAAGACCCAATAACAATACAAGAAAAAGTATACAGGTAGGACCAGGGAAAGCAATTTATACAACAGGAGAAATAATAGGAGATTTAAGACAAGCACATTGTAACCTTAGTAGAGCAGAATGGAATAACACTTTAAAACAGATAGTTAAGAAATTAAGAGAACAATTTGGGAATAAAACAATAGTCTTTAATCAATCCTCAGGAGGGGACCCAGAAATTGTAATGCACAGTTTGAATTGTAGAGGGGAATTTTTCTACTGTAATTCAACACAACTGTTTAATAGTACTTGGGATAATAGTACTTTGAATAATGTTACTGAAGGGTCAAATAGCACTGAAGAGAATATCACACTCCCATGCAGAATAAAACAAATTATAAACATGTGGCAGGAAGTAGGAAAAGCAATGTATGCCCCTCCCATCAGAGGACAAATTAGATGTTCATCAAATATTACAGGGCTGCTATTAACAAGAGATGGTGGTAAGGACACGAGCAATACCGAAATCTTCAGACCTGGA
            </sequences>
            <feature>
                <name>CDS</name>
                <type>aminoAcid</type>
                <coordinates>1-609</coordinates>
            </feature>
        </genome>

        <population>
            <populationSize>10000</populationSize>

            <inoculum>all</inoculum>
        </population>

        <fitnessFunction>
            <purifyingFitness>
                <feature>CDS</feature>
                <sites>1-203</sites>
                <rank>
                    <order>chemical</order>
                    <breakTies>random</breakTies>
                </rank>
                <fitness>
                    <betaDistributed>
                        <a>1.151</a>
                        <b>1.709</b>
                        <pLethal>0.4</pLethal>
                    </betaDistributed>
                </fitness>
            </purifyingFitness>
        </fitnessFunction>

        <mutator>
            <nucleotideMutator>
                <mutationRate>1.0E-4</mutationRate>
                <transitionBias>2.0</transitionBias>
            </nucleotideMutator>
        </mutator>

        <replicator>
            <clonalReplicator/>
        </replicator>

        <epoch>
            <generationCount>2001</generationCount>
        </epoch>

        <samplingSchedule>
            <sampler>
                <atFrequency>100</atFrequency>
                <fileName>purify_%r.nex</fileName>
                <alignment>
                    <schedule>
                        <!-- generation count -->
                        200 10
                        400 10
                        600 10
                        800 10
                        1000 10
                    </schedule>
                    <format>NEXUS</format>
                    <label>purifyBeta_%g_%s</label>
                </alignment>
            </sampler>
            <sampler>
                <atFrequency>10</atFrequency>
                <fileName>purifyingBeta_%r.csv</fileName>
                <statistics></statistics>
            </sampler>
        </samplingSchedule>
    </simulation>

</santa>
