=== sysrpl/SANTA-PENGUIN/examples/santa.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <xs:attributeGroup name="idable">
        <xs:attribute name="id" type="xs:ID"/>
        <xs:attribute name="ref" type="xs:NCName"/>
    </xs:attributeGroup>

    <xs:element name="santa">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="replicates" type="xs:string"/>
                <xs:element ref="simulation"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="simulation">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="genome"/>
                <xs:element ref="population"/>
                <xs:element ref="fitnessFunction"/>
                <xs:element ref="mutator"/>
                <xs:element ref="replicator"/>
                <xs:element minOccurs="1" maxOccurs="unbounded" ref="epoch"/>
                <xs:element ref="samplingSchedule"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="genome">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="length" type="xs:string"/>
                <xs:element minOccurs="0" name="sequences" type="xs:string"/>
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="feature"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="feature">
        <xs:complexType>
            <xs:all>
                <xs:element name="name" type="xs:string"/>
                <xs:element name="type">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="nucleotide"/>
                            <xs:enumeration value="aminoAcid"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="coordinates" type="xs:string"/>
            </xs:all>
        </xs:complexType>
    </xs:element>

    <xs:element name="population">
        <xs:complexType>
            <xs:all>
                <xs:element name="populationSize" type="xs:string"/>
                <xs:element name="inoculum">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="consensus"/>
                            <xs:enumeration value="random"/>
                            <xs:enumeration value="all"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
            </xs:all>
        </xs:complexType>
    </xs:element>

    <xs:element name="epoch">
        <xs:complexType>
            <xs:all>
                <xs:element minOccurs="0" name="name" type="xs:string"/>
                <xs:element name="generationCount" type="xs:string"/>
                <xs:element minOccurs="0" ref="fitnessFunction"/>
                <xs:element minOccurs="0" ref="mutator"/>
                <xs:element minOccurs="0" ref="replicator"/>
            </xs:all>
        </xs:complexType>
    </xs:element>

    <xs:element name="fitnessFunction">
        <xs:complexType>
            <xs:choice minOccurs="1" maxOccurs="unbounded">
                <xs:element ref="purifyingFitness"/>
                <xs:element ref="empiricalFitness"/>
                <xs:element ref="ageDependentFitness"/>
                <xs:element ref="exposureDependentFitness"/>
                <xs:element ref="populationSizeDependentFitness"/>
                <xs:element ref="frequencyDependentFitness"/>
                <xs:element ref="neutralFitness"/>
            </xs:choice>
            <xs:attributeGroup ref="idable"/>
        </xs:complexType>
    </xs:element>

    <xs:group name="feature-sites">
        <xs:sequence>
            <xs:element minOccurs="0" name="feature" type="xs:NCName"/>
            <xs:element minOccurs="0" name="sites" type="xs:string"/>
        </xs:sequence>
    </xs:group>

    <xs:element name="purifyingFitness">
        <xs:complexType>
            <xs:sequence minOccurs="0">
                <xs:group ref="feature-sites"/>
                <xs:element name="rank">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element minOccurs="1" maxOccurs="1" name="order" type="xs:string"/>
                            <xs:element minOccurs="0" maxOccurs="1" name="probableSet" type="xs:string"/>
                            <xs:element minOccurs="1" maxOccurs="1" name="breakTies">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="random"/>
                                        <xs:enumeration value="ordered"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="fitness">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:choice>
                                <xs:sequence>
                                    <xs:element name="lowFitness" type="xs:string"/>
                                    <xs:element name="minimumFitness" type="xs:string"/>
                                </xs:sequence>
                                <xs:element name="values" type="xs:string"/>
                                <xs:element name="betaDistributed">
                                    <xs:complexType>
                                        <xs:sequence>
                                            <xs:element name="a" type="xs:string"/>
                                            <xs:element name="b" type="xs:string"/>
                                            <xs:element name="pLethal" type="xs:string"/>
                                        </xs:sequence>
                                    </xs:complexType>
                                </xs:element>
                            </xs:choice>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element minOccurs="0" maxOccurs="1" name="fluctuate">
                    <xs:complexType>
                        <xs:all>
                            <xs:element name="fitnessLimit" type="xs:string"/>
                            <xs:element name="rate" type="xs:string"/>
                        </xs:all>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attributeGroup ref="idable"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="empiricalFitness">
        <xs:complexType>
            <xs:sequence minOccurs="0">
                <xs:group ref="feature-sites"/>
                <xs:element name="values" type="xs:string"/>
            </xs:sequence>
            <xs:attributeGroup ref="idable"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="ageDependentFitness">
        <xs:complexType>
            <xs:sequence minOccurs="0">
                <xs:group ref="feature-sites"/>
                <xs:element name="declineRate" type="xs:string"/>
            </xs:sequence>
            <xs:attributeGroup ref="idable"/>
        </xs:complexType>
    </xs:element>

<xs:element name="populationSizeDependentFitness">
        <xs:complexType>
            <xs:sequence minOccurs="0">
                <xs:group ref="feature-sites"/>
                <xs:element name="declineRate" type="xs:string"/>
                <xs:element name="maxPopulationSize" type="xs:string"/>
            </xs:sequence>
            <xs:attributeGroup ref="idable"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="exposureDependentFitness">
        <xs:complexType>
            <xs:sequence minOccurs="0">
                <xs:group ref="feature-sites"/>
                <xs:element name="penalty" type="xs:string"/>
            </xs:sequence>
            <xs:attributeGroup ref="idable"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="frequencyDependentFitness">
        <xs:complexType>
            <xs:sequence minOccurs="0">
                <xs:group ref="feature-sites"/>
                <xs:element name="shape" type="xs:string"/>
            </xs:sequence>
            <xs:attributeGroup ref="idable"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="neutralFitness">
        <xs:complexType>
            <xs:sequence minOccurs="0">
                <xs:group ref="feature-sites"/>
            </xs:sequence>
            <xs:attributeGroup ref="idable"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="mutator">
        <xs:complexType>
            <xs:all>
                <xs:element ref="nucleotideMutator"/>
            </xs:all>
        </xs:complexType>
    </xs:element>

    <xs:element name="nucleotideMutator">
        <xs:complexType>
            <xs:sequence minOccurs="0">
                <xs:element name="mutationRate" type="xs:string"/>
                <xs:choice>
                    <xs:element name="transitionBias" type="xs:string"/>
                    <xs:element name="rateBias" type="xs:string"/>
                </xs:choice>
            </xs:sequence>
            <xs:attributeGroup ref="idable"/>
        </xs:complexType>
    </xs:element>


    <xs:element name="replicator">
        <xs:complexType>
            <xs:choice>
                <xs:element ref="clonalReplicator"/>
                <xs:element ref="recombinantReplicator"/>
            </xs:choice>
        </xs:complexType>
    </xs:element>

    <xs:element name="clonalReplicator">
        <xs:complexType>
            <xs:attributeGroup ref="idable"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="recombinantReplicator">
        <xs:complexType>
            <xs:sequence minOccurs="0">
                <xs:element name="dualInfectionProbability" type="xs:string"/>
                <xs:element name="recombinationProbability" type="xs:string"/>
            </xs:sequence>
            <xs:attributeGroup ref="idable"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="samplingSchedule">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="sampler"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="sampler">
        <xs:complexType>
            <xs:sequence>
                <xs:choice>
                    <xs:element name="atFrequency" type="xs:string"/>
                    <xs:element name="atGeneration" type="xs:string"/>
                </xs:choice>
                <xs:element name="fileName" type="xs:string"/>
                <xs:choice>
                    <xs:element ref="alleleFrequency"/>
                    <xs:element ref="alignment"/>
                    <xs:element ref="tree"/>
                    <xs:element ref="statistics"/>
                </xs:choice>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="alleleFrequency">
        <xs:complexType>
            <xs:all>
                <xs:element minOccurs="0" name="feature" type="xs:string"/>
                <xs:element minOccurs="0" name="sites" type="xs:string"/>
            </xs:all>
        </xs:complexType>
    </xs:element>

    <xs:element name="alignment">
        <xs:complexType>
            <xs:sequence>
                <xs:choice>
                    <xs:element ref="schedule"/>
                    <xs:element name="sampleSize" type="xs:positiveInteger"/>
                </xs:choice>
                <xs:element name="format">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="NEXUS"/>
                            <xs:enumeration value="FASTA"/>
                            <xs:enumeration value="XML"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element minOccurs="0" maxOccurs="1" name="label" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="tree">
        <xs:complexType>
            <xs:sequence>
                <xs:choice>
                    <xs:element ref="schedule"/>
                    <xs:element name="sampleSize" type="xs:positiveInteger"/>
                </xs:choice>
                <xs:element name="format">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="NEXUS"/>
                            <xs:enumeration value="NEWICK"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element minOccurs="0" maxOccurs="1" name="label" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="schedule">
        <xs:simpleType>
            <xs:list itemType="xs:positiveInteger"/>
        </xs:simpleType>
    </xs:element>

    <xs:element name="statistics"/>
</xs:schema>

=== sysrpl/SANTA-PENGUIN/examples/agedependent.xml
<santa xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="santa.xsd">
	<replicates>1</replicates>

	<simulation>
		<genome>
			<length>609</length>
			<sequences>
				GAAGAAGAGGTAGTAATTAGATCTGAAAATTTCACGGACAATGCTAAAACCATAATAGTACAGCTGAAGGAGTCTGTAGTAATTAATTGTACAAGACCCAATAACAATACAAGAAAAAGTATACAGGTAGGACCAGGGAAAGCAATTTATACAACAGGAGAAATAATAGGAGATTTAAGACAAGCACATTGTAACCTTAGTAGAGCAGAATGGAATAACACTTTAAAACAGATAGTTAAGAAATTAAGAGAACAATTTGGGAATAAAACAATAGTCTTTAATCAATCCTCAGGAGGGGACCCAGAAATTGTAATGCACAGTTTGAATTGTAGAGGGGAATTTTTCTACTGTAATTCAACACAACTGTTTAATAGTACTTGGGATAATAGTACTTTGAATAATGTTACTGAAGGGTCAAATAGCACTGAAGAGAATATCACACTCCCATGCAGAATAAAACAAATTATAAACATGTGGCAGGAAGTAGGAAAAGCAATGTATGCCCCTCCCATCAGAGGACAAATTAGATGTTCATCAAATATTACAGGGCTGCTATTAACAAGAGATGGTGGTAAGGACACGAGCAATACCGAAATCTTCAGACCTGGA
			</sequences>
            <feature>
            	<name>CDS</name>
            	<type>aminoAcid</type>
            	<coordinates>1-609</coordinates>
           	</feature>
		</genome>

		<population>
			<populationSize>10000</populationSize>
			<inoculum>all</inoculum>
		</population>

		<fitnessFunction>
			<ageDependentFitness>
				<feature>CDS</feature>
				<sites>1-5</sites>
				<declineRate>0.005</declineRate>
			</ageDependentFitness>
		</fitnessFunction>

		<mutator>
			<nucleotideMutator>
				<mutationRate>1.0E-4</mutationRate>
				<transitionBias>2.0</transitionBias>
			</nucleotideMutator>
		</mutator>

		<replicator>
			<clonalReplicator/>
		</replicator>

		<epoch>
			<generationCount>1000</generationCount>
		</epoch>

		<samplingSchedule>
			<sampler>
				<atFrequency>100</atFrequency>
				<fileName>age_%r.nex</fileName>
				<alignment>
					<schedule>
						<!-- generation count -->
						200  10
						400  10
						600  10
						800  10
						1000  10
					</schedule>
					<format>NEXUS</format>
					<label>age_%g_%s</label>
				</alignment>
			</sampler>
			<sampler>
				<atFrequency>1</atFrequency>
				<fileName>age_%r.csv</fileName>
				<statistics></statistics>
			</sampler>
		</samplingSchedule>

	</simulation>

</santa>

=== sysrpl/SANTA-PENGUIN/examples/footprint.xml
<santa xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="santa.xsd">
    <replicates>1</replicates>

    <simulation>
        <genome>
            <length>999</length>
	        <sequences>
		        AGTGAAGAAGAGGTAGTAATTAGATCTGAAAATTTCACGGACAATGCTAAAACCATAATAGTACAGCTGAAGGAGTCTGTAGTAATTAATTGTACAAGACCCAATAACAATACAAGAAAAAGTATACAGGTAGGACCAGGGAAAGCAATTTATACAACAGGAGAAATAATAGGAGATTTAAGACAAGCACATTGTAACCTTAGTAGAGCAGAATGGAATAACACTTTAAAACAGATAGTTAAGAAATTAAGAGAACAATTTGGGAATAAAACAATAGTCTTTAATCAATCCTCAGGAGGGGACCCAGAAATTGTAATGCACAGTTTGAATTGTAGAGGGGAATTTTTCTACTGTAATTCAACACAACTGTTTAATAGTACTTGGGATAATAGTACTTTGAATAATGTTACTGAAGGGTCAAATAGCACTGAAGAGAATATCACACTCCCATGCAGAATAAAACAAATTATAAACATGTGGCAGGAAGGAAAAGCAATGGTATATGCCCCTCCCATCAGAGGACAAATTAGATGTTCATCAAATATTACAGGGCTGCTATTAACAAGAGATGGTGGTAAGGACACGAGCAATACCGAAATCTTCAGACCTGGAGAAGAAGAGGTAGTAATTAGATCTGAAAATTTCACGGACAATGCTAAAACCATAATAGTACAGCTGAAGGAGTCTGTAGTAATTAATTGTACAAGACCCAATAACAATACAAGAAAAAGTATACAGGTAGGACCAGGGAAAGCAATTTATACAACAGGAGAAATAATAGGAGATTTAAGACAAGCACATTGTAACCTTAGTAGAGCAGAATGGAATAACACTTTAAAACAGATAGTTAAGAAATTAAGAGAACAATTTGGGAATAAAACAATAGTCTTTAATCAATCCTCAGGAGGGGACCCAGAAATTGTAATGCACAGTTTGAATTGTAGAGGGGAATTTTTCTACTGTAATTCAACACAACTGTTTAATAGTACTTGGGATAAT
	        </sequences>
	        <feature>
		        <name>CDS</name>
		        <type>aminoAcid</type>
		        <coordinates>1-999</coordinates>
	        </feature>
        </genome>

        <population>
            <populationSize>1000</populationSize>

            <inoculum>all</inoculum>
        </population>

        <fitnessFunction>
            <purifyingFitness>
	            <feature>CDS</feature>
                <sites>1-166,168-333</sites>
                <rank>
                	<order>observed</order>
                    <breakTies>random</breakTies>
                </rank>
                <fitness>
	                <lowFitness>0.5</lowFitness>
                    <minimumFitness>0.5</minimumFitness>
                </fitness>
            </purifyingFitness>
            <purifyingFitness>
	            <feature>CDS</feature>
                <sites>167</sites>
                <rank>
                    <order>VL</order>
                    <breakTies>random</breakTies>
                </rank>
                <fitness>
	                <lowFitness>0.1</lowFitness>
                    <minimumFitness>0.0</minimumFitness>
                </fitness>
                <fluctuate>
                    <rate>$rate</rate>
                    <fitnessLimit>0.1</fitnessLimit>
                </fluctuate>
            </purifyingFitness>
        </fitnessFunction>

        <mutator>
            <nucleotideMutator>
                <mutationRate>2.5E-4</mutationRate>
                <transitionBias>2.0</transitionBias>
            </nucleotideMutator>
        </mutator>

        <replicator>
            <recombinantReplicator>
                <dualInfectionProbability>$dual</dualInfectionProbability>
                <recombinationProbability>0.001</recombinationProbability>
            </recombinantReplicator>

        </replicator>

        <epoch>
            <generationCount>1000000</generationCount>
        </epoch>

        <samplingSchedule>
            <sampler>
                <atFrequency>1000</atFrequency>
                <fileName>alignment_%r.nex</fileName>
                <alignment>
                    <sampleSize>100</sampleSize>
                    <format>NEXUS</format>
                    <label>seq_%g_%s</label>
                </alignment>
            </sampler>
            <sampler>
                <atFrequency>1000</atFrequency>
                <fileName>aa_frequencies.csv</fileName>
                <alleleFrequency>
	                <feature>CDS</feature>
                </alleleFrequency>
            </sampler>
            <sampler>
                <atFrequency>1000</atFrequency>
                <fileName>nt_frequencies.csv</fileName>
                <alleleFrequency>
                    <sites>1-999</sites>
                </alleleFrequency>
            </sampler>
            <sampler>
                <atFrequency>1</atFrequency>
                <fileName>stats.csv</fileName>
                <statistics></statistics>
            </sampler>
        </samplingSchedule>

    </simulation>

</santa>

=== sysrpl/SANTA-PENGUIN/examples/small-indel.xml
<santa xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="santa.xsd">
  <replicates>1</replicates>

  <simulation>

    <genome>
      <length>18</length>
      <sequences>
	GAAGAAGAGGAAGAAGAG
      </sequences>
      <feature>
	<name>CDS</name>
	<type>aminoAcid</type>
	<coordinates>1-9</coordinates>
      </feature>
    </genome>

    <population>
      <populationSize>$population</populationSize>
      <inoculum>all</inoculum>
    </population>
    <populationType>staticPopulation</populationType>

    <fitnessFunction>
      <neutralFitness>
        <sites>1-9</sites>
      </neutralFitness>
      <purifyingFitness>
	<feature>CDS</feature>
	<sites>1</sites>
	<rank>
	  <order>observed</order>
	  <probableSet>2</probableSet>
	  <breakTies>random</breakTies>
	</rank>
	<fitness>
	  <lowFitness>0.1</lowFitness>
	  <minimumFitness>0.1</minimumFitness>
	</fitness>

      </purifyingFitness>
    </fitnessFunction>

    <mutator>
      <nucleotideMutator>
	<mutationRate>1.0E-4</mutationRate>
	<transitionBias>2.0</transitionBias>

	<indelmodel model="NB">0.4 1</indelmodel>
	<insertprob>2.5E-2</insertprob>
	<deleteprob>2.5E-2</deleteprob>

      </nucleotideMutator>
    </mutator>

    <replicator>
      <clonalReplicator/>
    </replicator>

    <epoch>
      <name>initial</name>
      <generationCount>$generations</generationCount>			
    </epoch>

    <samplingSchedule>
      <sampler>
	<atFrequency>1</atFrequency>	
	<fileName>sequences_%r.fa</fileName>
	<alignment>
	  <sampleSize>$samplesize</sampleSize>
	  <format>FASTA</format>
	  <label>sequence_%g_%s|hiv_pol.fa|0|0</label>
	</alignment>
      </sampler>
      <sampler>
	<atFrequency>10</atFrequency>	
      	<fileName>trees.nex</fileName>
      	<tree>
      	  <sampleSize>$samplesize</sampleSize>
      	  <format>NEXUS</format>
      	  <label>tip_%s</label>
      	</tree>
      </sampler>
   </samplingSchedule>

  </simulation>

</santa>

=== sysrpl/SANTA-PENGUIN/examples/indel_test.xml
<santa xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="santa.xsd">

  <!-- Using run-time parameters -->

  <!-- The configuration file supports the use of parameters, for which -->
  <!-- values may be defined at run time. This may be done for all numberic -->
  <!-- configuration parameters. Parameters must start with a '$' sign. -->
  <replicates>$replicates</replicates>

  <simulation>
    <genome>
      
      <length>210</length>
      
      <sequences>
> HIV-1.POL_0_|0|0|0
ATGAGTTTGCCAGGAAGATGGAAACCAAAAATGATAGGGGGAATTGGAGGTTTTATCAAAGTAAGACAGT
ATGATCAGATACTCATAGAAATCTGTGGACATAAAGCTATAGGTACAGTATTAGTAGGACCTACACCTGT
CAACATAATTGGAAGAAATCTGTTGACTCAGATTGGTTGCACTTTAAATTTTCCCATTAGCCCTATTGAG
      </sequences>
      <feature>
      	<name>PR</name>
      	<type>aminoAcid</type>
      	<coordinates>27-62</coordinates>
      </feature>
      <feature>
      	<name>CDS</name>
      	<type>aminoAcid</type>
      	<coordinates>61-123</coordinates>
      </feature>
    </genome>

    <population>
      <populationSize>$population</populationSize>
      <inoculum>all</inoculum>
    </population>
    <populationType>staticPopulation</populationType>

    <fitnessFunction>
      <purifyingFitness>
      	<feature>CDS</feature>
        <sites>1</sites>
        <rank>
          <order>chemical</order>
          <breakTies>random</breakTies>
        </rank>
        <fitness>
          <lowFitness>0.9</lowFitness>
      	  <minimumFitness>0.1</minimumFitness>
        </fitness>
      </purifyingFitness>
      <!-- <purifyingFitness> -->
      <!-- 	<feature>CDS</feature> -->
      <!--   <sites>10-20</sites> -->
      <!--   <rank> -->
      <!--     <order>chemical</order> -->
      <!--     <breakTies>random</breakTies> -->
      <!--   </rank> -->
      <!--   <fitness> -->
      <!--     <lowFitness>0.9</lowFitness> -->
      <!-- 	  <minimumFitness>0.1</minimumFitness> -->
      <!--   </fitness> -->
      <!-- </purifyingFitness> -->
      <!-- <populationSizeDependentFitness> -->
      <!-- 	<feature>PR</feature> -->
      <!-- 	<sites>1-30</sites> -->
      <!-- 	<declineRate>0.005</declineRate> -->
      <!-- 	<maxPopulationSize>50000</maxPopulationSize> -->
      <!-- </populationSizeDependentFitness> -->
      <!-- <exposureDependentFitness> -->
      <!-- 	<feature>CDS</feature> -->
      <!-- 	<sites>1-5</sites> -->
      <!-- 	<penalty>0.01</penalty> -->
      <!-- </exposureDependentFitness> -->

    </fitnessFunction>

    <!-- Mutations occur as an independent process after replication,
         The user specifies a per-site and per-generation probability
         of mutation, and the mutator component then applies mutations
         to the genome accordingly. For efficiency, the default
         mutator draws the number of mutations from a Poisson
         distribution with an expectation given by the number of
         nucleotides and the rate. These are then distributed
         uniformly across sites. A bias towards transition-type
         mutations can be specified to reflect the action of some
         polymerases, or all 12 relative rates biases may be specified
         -->
    <mutator>
      <nucleotideMutator>
	<mutationRate>2.5e-5</mutationRate>

	<!-- Negative Binomial
	     Geometric insertion length distribution (q=0.4, r=1) -->
	<indelmodel model="NB">0.4 1</indelmodel>
	<insertprob>2.5E-1</insertprob>
	<deleteprob>2.5E-1</deleteprob>
	<!-- Negative binomial
	     Pascal insertion length distribution (q=0.2, r=4) -->
	<!-- <delete model="NB">0.2 4</delete> -->	
	<rateBias>
	  0.42 2.49 0.29
	  1.73 0.23 4.73
	  6.99 0.20 0.60
	  1.02 2.56 0.88
	</rateBias>
      </nucleotideMutator>
    </mutator>
    <replicator>
      <recombinantReplicator>
      	<dualInfectionProbability>0.99</dualInfectionProbability>
      	<recombinationProbability>0.01</recombinationProbability>
      </recombinantReplicator>
      <!-- <clonalReplicator/> -->
    </replicator>

    <epoch>
      <name>initial</name>
      <generationCount>$generations</generationCount>			
    </epoch>
    
    <samplingSchedule>
      <sampler>
      	<atGeneration>1</atGeneration>
      	<fileName>trees_%r.tree</fileName>
      	<tree>
      	  <sampleSize>5</sampleSize>
      	  <format>NEXUS</format>
      	  <label>tip_%g_%s</label>
      	</tree>
      </sampler>
      <sampler>
	<atFrequency>1</atFrequency>	
	<fileName>sequences_%r.fa</fileName>
	<alignment>
	  <sampleSize>$samplesize</sampleSize>
	  <format>FASTA</format>
	  <label>sequence_%g_%s|hiv_pol.fa|0|0</label>
	</alignment>
      </sampler>
      <sampler>
      	<atFrequency>1</atFrequency>
      	<fileName>genomes_%r.tsv</fileName>
      	<genomedescription>
      	  <sampleSize>10000</sampleSize>
      	  <label>genome_%g_%s</label>
      	</genomedescription>
      </sampler>
    </samplingSchedule>

    <eventLogger>
      <fileName>events.txt</fileName>
    </eventLogger>
  </simulation>
</santa>
