=== sysrpl/SANTA-PENGUIN/examples/santa.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <xs:attributeGroup name="idable">
        <xs:attribute name="id" type="xs:ID"/>
        <xs:attribute name="ref" type="xs:NCName"/>
    </xs:attributeGroup>

    <xs:element name="santa">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="replicates" type="xs:string"/>
                <xs:element ref="simulation"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="simulation">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="genome"/>
                <xs:element ref="population"/>
                <xs:element ref="fitnessFunction"/>
                <xs:element ref="mutator"/>
                <xs:element ref="replicator"/>
                <xs:element minOccurs="1" maxOccurs="unbounded" ref="epoch"/>
                <xs:element ref="samplingSchedule"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="genome">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="length" type="xs:string"/>
                <xs:element minOccurs="0" name="sequences" type="xs:string"/>
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="feature"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="feature">
        <xs:complexType>
            <xs:all>
                <xs:element name="name" type="xs:string"/>
                <xs:element name="type">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="nucleotide"/>
                            <xs:enumeration value="aminoAcid"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="coordinates" type="xs:string"/>
            </xs:all>
        </xs:complexType>
    </xs:element>

    <xs:element name="population">
        <xs:complexType>
            <xs:all>
                <xs:element name="populationSize" type="xs:string"/>
                <xs:element name="inoculum">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="consensus"/>
                            <xs:enumeration value="random"/>
                            <xs:enumeration value="all"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
            </xs:all>
        </xs:complexType>
    </xs:element>

    <xs:element name="epoch">
        <xs:complexType>
            <xs:all>
                <xs:element minOccurs="0" name="name" type="xs:string"/>
                <xs:element name="generationCount" type="xs:string"/>
                <xs:element minOccurs="0" ref="fitnessFunction"/>
                <xs:element minOccurs="0" ref="mutator"/>
                <xs:element minOccurs="0" ref="replicator"/>
            </xs:all>
        </xs:complexType>
    </xs:element>

    <xs:element name="fitnessFunction">
        <xs:complexType>
            <xs:choice minOccurs="1" maxOccurs="unbounded">
                <xs:element ref="purifyingFitness"/>
                <xs:element ref="empiricalFitness"/>
                <xs:element ref="ageDependentFitness"/>
                <xs:element ref="exposureDependentFitness"/>
                <xs:element ref="populationSizeDependentFitness"/>
                <xs:element ref="frequencyDependentFitness"/>
                <xs:element ref="neutralFitness"/>
            </xs:choice>
            <xs:attributeGroup ref="idable"/>
        </xs:complexType>
    </xs:element>

    <xs:group name="feature-sites">
        <xs:sequence>
            <xs:element minOccurs="0" name="feature" type="xs:NCName"/>
            <xs:element minOccurs="0" name="sites" type="xs:string"/>
        </xs:sequence>
    </xs:group>

    <xs:element name="purifyingFitness">
        <xs:complexType>
            <xs:sequence minOccurs="0">
                <xs:group ref="feature-sites"/>
                <xs:element name="rank">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element minOccurs="1" maxOccurs="1" name="order" type="xs:string"/>
                            <xs:element minOccurs="0" maxOccurs="1" name="probableSet" type="xs:string"/>
                            <xs:element minOccurs="1" maxOccurs="1" name="breakTies">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="random"/>
                                        <xs:enumeration value="ordered"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="fitness">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:choice>
                                <xs:sequence>
                                    <xs:element name="lowFitness" type="xs:string"/>
                                    <xs:element name="minimumFitness" type="xs:string"/>
                                </xs:sequence>
                                <xs:element name="values" type="xs:string"/>
                                <xs:element name="betaDistributed">
                                    <xs:complexType>
                                        <xs:sequence>
                                            <xs:element name="a" type="xs:string"/>
                                            <xs:element name="b" type="xs:string"/>
                                            <xs:element name="pLethal" type="xs:string"/>
                                        </xs:sequence>
                                    </xs:complexType>
                                </xs:element>
                            </xs:choice>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element minOccurs="0" maxOccurs="1" name="fluctuate">
                    <xs:complexType>
                        <xs:all>
                            <xs:element name="fitnessLimit" type="xs:string"/>
                            <xs:element name="rate" type="xs:string"/>
                        </xs:all>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attributeGroup ref="idable"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="empiricalFitness">
        <xs:complexType>
            <xs:sequence minOccurs="0">
                <xs:group ref="feature-sites"/>
                <xs:element name="values" type="xs:string"/>
            </xs:sequence>
            <xs:attributeGroup ref="idable"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="ageDependentFitness">
        <xs:complexType>
            <xs:sequence minOccurs="0">
                <xs:group ref="feature-sites"/>
                <xs:element name="declineRate" type="xs:string"/>
            </xs:sequence>
            <xs:attributeGroup ref="idable"/>
        </xs:complexType>
    </xs:element>

<xs:element name="populationSizeDependentFitness">
        <xs:complexType>
            <xs:sequence minOccurs="0">
                <xs:group ref="feature-sites"/>
                <xs:element name="declineRate" type="xs:string"/>
                <xs:element name="maxPopulationSize" type="xs:string"/>
            </xs:sequence>
            <xs:attributeGroup ref="idable"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="exposureDependentFitness">
        <xs:complexType>
            <xs:sequence minOccurs="0">
                <xs:group ref="feature-sites"/>
                <xs:element name="penalty" type="xs:string"/>
            </xs:sequence>
            <xs:attributeGroup ref="idable"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="frequencyDependentFitness">
        <xs:complexType>
            <xs:sequence minOccurs="0">
                <xs:group ref="feature-sites"/>
                <xs:element name="shape" type="xs:string"/>
            </xs:sequence>
            <xs:attributeGroup ref="idable"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="neutralFitness">
        <xs:complexType>
            <xs:sequence minOccurs="0">
                <xs:group ref="feature-sites"/>
            </xs:sequence>
            <xs:attributeGroup ref="idable"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="mutator">
        <xs:complexType>
            <xs:all>
                <xs:element ref="nucleotideMutator"/>
            </xs:all>
        </xs:complexType>
    </xs:element>

    <xs:element name="nucleotideMutator">
        <xs:complexType>
            <xs:sequence minOccurs="0">
                <xs:element name="mutationRate" type="xs:string"/>
                <xs:choice>
                    <xs:element name="transitionBias" type="xs:string"/>
                    <xs:element name="rateBias" type="xs:string"/>
                </xs:choice>
            </xs:sequence>
            <xs:attributeGroup ref="idable"/>
        </xs:complexType>
    </xs:element>


    <xs:element name="replicator">
        <xs:complexType>
            <xs:choice>
                <xs:element ref="clonalReplicator"/>
                <xs:element ref="recombinantReplicator"/>
            </xs:choice>
        </xs:complexType>
    </xs:element>

    <xs:element name="clonalReplicator">
        <xs:complexType>
            <xs:attributeGroup ref="idable"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="recombinantReplicator">
        <xs:complexType>
            <xs:sequence minOccurs="0">
                <xs:element name="dualInfectionProbability" type="xs:string"/>
                <xs:element name="recombinationProbability" type="xs:string"/>
            </xs:sequence>
            <xs:attributeGroup ref="idable"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="samplingSchedule">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="sampler"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="sampler">
        <xs:complexType>
            <xs:sequence>
                <xs:choice>
                    <xs:element name="atFrequency" type="xs:string"/>
                    <xs:element name="atGeneration" type="xs:string"/>
                </xs:choice>
                <xs:element name="fileName" type="xs:string"/>
                <xs:choice>
                    <xs:element ref="alleleFrequency"/>
                    <xs:element ref="alignment"/>
                    <xs:element ref="tree"/>
                    <xs:element ref="statistics"/>
                </xs:choice>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="alleleFrequency">
        <xs:complexType>
            <xs:all>
                <xs:element minOccurs="0" name="feature" type="xs:string"/>
                <xs:element minOccurs="0" name="sites" type="xs:string"/>
            </xs:all>
        </xs:complexType>
    </xs:element>

    <xs:element name="alignment">
        <xs:complexType>
            <xs:sequence>
                <xs:choice>
                    <xs:element ref="schedule"/>
                    <xs:element name="sampleSize" type="xs:positiveInteger"/>
                </xs:choice>
                <xs:element name="format">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="NEXUS"/>
                            <xs:enumeration value="FASTA"/>
                            <xs:enumeration value="XML"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element minOccurs="0" maxOccurs="1" name="label" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="tree">
        <xs:complexType>
            <xs:sequence>
                <xs:choice>
                    <xs:element ref="schedule"/>
                    <xs:element name="sampleSize" type="xs:positiveInteger"/>
                </xs:choice>
                <xs:element name="format">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="NEXUS"/>
                            <xs:enumeration value="NEWICK"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element minOccurs="0" maxOccurs="1" name="label" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="schedule">
        <xs:simpleType>
            <xs:list itemType="xs:positiveInteger"/>
        </xs:simpleType>
    </xs:element>

    <xs:element name="statistics"/>
</xs:schema>

=== sysrpl/SANTA-PENGUIN/examples/sweep.xml
<santa xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="santa.xsd">
  <replicates>1</replicates>
  <simulation>
    <genome>
      <length>609</length>
      <sequences>
	GAAGAAGAGGTAGTAATTAGATCTGAAAATTTCACGGACAATGCTAAAACCATAATAGTACAGCTGAAGGAGTCTGTAGTAATTAATTGTACAAGACCCAATAACAATACAAGAAAAAGTATACAGGTAGGACCAGGGAAAGCAATTTATACAACAGGAGAAATAATAGGAGATTTAAGACAAGCACATTGTAACCTTAGTAGAGCAGAATGGAATAACACTTTAAAACAGATAGTTAAGAAATTAAGAGAACAATTTGGGAATAAAACAATAGTCTTTAATCAATCCTCAGGAGGGGACCCAGAAATTGTAATGCACAGTTTGAATTGTAGAGGGGAATTTTTCTACTGTAATTCAACACAACTGTTTAATAGTACTTGGGATAATAGTACTTTGAATAATGTTACTGAAGGGTCAAATAGCACTGAAGAGAATATCACACTCCCATGCAGAATAAAACAAATTATAAACATGTGGCAGGAAGTAGGAAAAGCAATGTATGCCCCTCCCATCAGAGGACAAATTAGATGTTCATCAAATATTACAGGGCTGCTATTAACAAGAGATGGTGGTAAGGACACGAGCAATACCGAAATCTTCAGACCTGGA
      </sequences>
      <feature>
	<name>CDS</name>
	<type>aminoAcid</type>
	<coordinates>1-609</coordinates>
      </feature>
    </genome>

    <population>
      <populationSize>$population</populationSize>

      <inoculum>all</inoculum>
    </population>

    <fitnessFunction>
      <empiricalFitness>
	<feature>CDS</feature>
	<sites>100</sites>

	<!-- assign fitness 1 to K, 0.85 to N, and 0.01 to all other amino acids -->
	<values>
	  0.01 <!-- A -->
	  0.01 <!-- C -->
	  0.01 <!-- D -->
	  0.01 <!-- E -->
	  0.01 <!-- F-->
	  0.01 <!-- G -->
	  0.01 <!-- H -->
	  0.01 <!-- I -->
	  0.02    <!-- K -->
	  0.01 <!-- L -->
	  0.01 <!-- M -->
	  0.01 <!-- N -->
	  0.01 <!-- P -->
	  0.01 <!-- Q -->
	  0.01 <!-- R -->
	  0.01 <!-- S -->
	  0.01 <!-- T -->
	  0.01 <!-- V -->
	  0.01 <!-- W -->
	  0.01 <!-- Y -->
	</values>
      </empiricalFitness>
    </fitnessFunction>
    <mutator>
      <nucleotideMutator>
	<mutationRate>1.0E-4</mutationRate>
	<transitionBias>2.0</transitionBias>
      </nucleotideMutator>
      <!-- <oneoff> -->
      <!-- 	<generation>1000</generation> -->
      <!-- 	<feature>CDS</feature> -->
      <!-- 	<sites>100</sites> -->
      <!-- 	<symbols>K</symbols> -->
      <!-- </onoff> -->
    </mutator>

    <replicator>
      <recombinantReplicator>
      	<dualInfectionProbability>1</dualInfectionProbability>
      	<recombinationProbability>0.01</recombinationProbability>
      </recombinantReplicator>
    </replicator>

    <epoch>
      <generationCount>$generations</generationCount>
    </epoch>

    <samplingSchedule>
      <sampler>
	<atFrequency>10</atFrequency>
	<fileName>frequency_%r.csv</fileName>
	<statistics></statistics>
      </sampler>
      <sampler>
	<atFrequency>1</atFrequency>	
	<fileName>sequences_%r.fa</fileName>
	<alignment>
	  <sampleSize>$samplesize</sampleSize>
	  <format>FASTA</format>
	  <label>sequence_%g_%s</label>
	</alignment>
      </sampler>
    </samplingSchedule>

  </simulation>

</santa>
